/**
 * NutriSense AI — Legal Screen
 * Terms of Service and Privacy Policy for App Store review compliance.
 * Route: /legal?tab=terms | /legal?tab=privacy
 */

import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS } from '@/constants';

const COMPANY_NAME = 'NutriSense AI, Inc.';
const APP_NAME = 'NutriSense AI';
const CONTACT_EMAIL = 'legal@nutrisenseai.com';
const EFFECTIVE_DATE = 'May 1, 2025';
const WEBSITE = 'https://nutrisenseai.com';

// ============================================================
// Terms of Service
// ============================================================
function TermsOfService() {
  return (
    <View style={{ gap: 20 }}>
      <Text style={{ fontSize: 22, fontWeight: '800', color: COLORS.text.primary }}>
        Terms of Service
      </Text>
      <Text style={{ fontSize: 12, color: COLORS.text.muted }}>
        Effective Date: {EFFECTIVE_DATE} | {COMPANY_NAME}
      </Text>

      {[
        {
          title: '1. Acceptance of Terms',
          body: `By downloading, installing, or using ${APP_NAME} ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App. These Terms constitute a legally binding agreement between you and ${COMPANY_NAME} ("Company", "we", "us", or "our").`,
        },
        {
          title: '2. Description of Service',
          body: `${APP_NAME} is an AI-powered nutrition tracking mobile application that provides food analysis, macro tracking, fridge inventory management, and recipe generation features. The App uses artificial intelligence and computer vision to estimate nutritional content from photographs. All nutritional estimates are approximations and should not be used as a substitute for professional medical or dietary advice.`,
        },
        {
          title: '3. User Accounts',
          body: `You must create an account to use the App. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during registration. You must be at least 13 years of age to create an account. If you are under 18, you represent that you have parental or guardian consent.`,
        },
        {
          title: '4. In-App Purchases & Pro Pack',
          body: `The App offers a one-time "Pro Pack" lifetime purchase for $29.00 USD, as well as optional Educational Modules and Consultation Vouchers. All purchases are processed through Apple App Store or Google Play Store and are subject to their respective terms. All sales are final. Refunds are handled exclusively by Apple or Google per their refund policies. ${COMPANY_NAME} does not process refunds directly. The Pro Pack grants lifetime access to premium features as described at the time of purchase. ${COMPANY_NAME} reserves the right to modify, add, or remove features with reasonable notice.`,
        },
        {
          title: '5. AI-Generated Content Disclaimer',
          body: `The nutritional information, health snippets, allergen flags, and recipe suggestions generated by the App's AI systems are estimates based on visual analysis and publicly available nutritional databases. This information is provided for general informational purposes only and does not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider or registered dietitian before making significant dietary changes, especially if you have medical conditions, allergies, or specific health goals. ${COMPANY_NAME} expressly disclaims all liability for any health consequences arising from reliance on AI-generated nutritional estimates.`,
        },
        {
          title: '6. Allergen Warning',
          body: `While ${APP_NAME} attempts to identify common allergens in food items, the AI system may not detect all allergens in all circumstances. Users with severe food allergies must not rely solely on the App for allergen identification. Always verify ingredients directly with food manufacturers and consult your healthcare provider regarding your specific allergen management plan.`,
        },
        {
          title: '7. Prohibited Uses',
          body: `You agree not to: (a) use the App for any unlawful purpose; (b) attempt to reverse engineer, decompile, or disassemble the App; (c) use automated tools to scrape or harvest data from the App; (d) impersonate any person or entity; (e) upload content that infringes any third-party intellectual property rights; (f) use the App to transmit malware or harmful code; (g) attempt to gain unauthorized access to any portion of the App or its infrastructure.`,
        },
        {
          title: '8. Intellectual Property',
          body: `All content, features, and functionality of the App, including but not limited to text, graphics, logos, and software, are owned by ${COMPANY_NAME} and are protected by applicable intellectual property laws. You are granted a limited, non-exclusive, non-transferable license to use the App for personal, non-commercial purposes.`,
        },
        {
          title: '9. User-Generated Content',
          body: `By uploading photographs or other content to the App, you grant ${COMPANY_NAME} a non-exclusive, royalty-free license to use such content solely for the purpose of providing the App's services, including AI analysis. We do not sell your personal photographs to third parties. Food images may be used in anonymized, aggregated form to improve AI model accuracy.`,
        },
        {
          title: '10. Limitation of Liability',
          body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ${COMPANY_NAME.toUpperCase()} SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR HEALTH OUTCOMES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE APP. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE APP IN THE TWELVE MONTHS PRECEDING THE CLAIM.`,
        },
        {
          title: '11. Termination',
          body: `${COMPANY_NAME} reserves the right to suspend or terminate your account at any time for violation of these Terms. Upon termination, your right to use the App will immediately cease. Provisions that by their nature should survive termination shall survive, including intellectual property provisions, disclaimers, and limitations of liability.`,
        },
        {
          title: '12. Governing Law',
          body: `These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any disputes shall be resolved through binding arbitration in accordance with the American Arbitration Association rules, except that either party may seek injunctive relief in a court of competent jurisdiction.`,
        },
        {
          title: '13. Changes to Terms',
          body: `${COMPANY_NAME} reserves the right to modify these Terms at any time. We will provide notice of material changes through the App or via email. Your continued use of the App after such notice constitutes acceptance of the updated Terms.`,
        },
        {
          title: '14. Contact',
          body: `For questions regarding these Terms, contact us at:\n${COMPANY_NAME}\nEmail: ${CONTACT_EMAIL}\nWebsite: ${WEBSITE}`,
        },
      ].map(({ title, body }) => (
        <View key={title}>
          <Text style={{ fontSize: 15, fontWeight: '700', color: COLORS.text.primary, marginBottom: 6 }}>
            {title}
          </Text>
          <Text style={{ fontSize: 14, color: COLORS.text.secondary, lineHeight: 22 }}>
            {body}
          </Text>
        </View>
      ))}
    </View>
  );
}

// ============================================================
// Privacy Policy
// ============================================================
function PrivacyPolicy() {
  return (
    <View style={{ gap: 20 }}>
      <Text style={{ fontSize: 22, fontWeight: '800', color: COLORS.text.primary }}>
        Privacy Policy
      </Text>
      <Text style={{ fontSize: 12, color: COLORS.text.muted }}>
        Effective Date: {EFFECTIVE_DATE} | {COMPANY_NAME}
      </Text>

      {[
        {
          title: '1. Introduction',
          body: `${COMPANY_NAME} ("we", "us", or "our") operates the ${APP_NAME} mobile application. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you use our App. By using the App, you consent to the practices described in this Policy.`,
        },
        {
          title: '2. Information We Collect',
          body: `We collect the following categories of information:\n\n• Account Information: Email address, display name, and password (hashed).\n• Profile Data: Age, gender, height, weight, dietary restrictions, allergens, and nutrition goals.\n• Food Log Data: Photographs of food, nutritional logs, meal timestamps, and barcode scans.\n• Fridge Inventory: Item names, quantities, and expiration dates.\n• Device Information: Device type, operating system, app version, and unique device identifiers.\n• Usage Data: Feature interactions, session duration, and crash reports.\n• Purchase Data: Transaction IDs and entitlement status (processed by Apple/Google; we do not store payment card information).`,
        },
        {
          title: '3. How We Use Your Information',
          body: `We use your information to:\n\n• Provide and improve the App's AI food analysis, macro tracking, and recipe generation features.\n• Personalize your nutrition goals and dietary recommendations.\n• Process and verify in-app purchases through RevenueCat.\n• Send push notifications for expiry alerts and coaching reminders (with your consent).\n• Analyze aggregate, anonymized usage patterns to improve AI model accuracy.\n• Comply with legal obligations and enforce our Terms of Service.\n• Respond to customer support inquiries.`,
        },
        {
          title: '4. Food Photographs & AI Processing',
          body: `When you photograph food for analysis, the image is transmitted securely to our AI processing infrastructure (powered by OpenAI's vision API). Images are processed in real-time and are not permanently stored on our servers unless you explicitly save a food log entry with an image. Stored images are associated with your account and are not shared with third parties for advertising purposes. We may use anonymized, aggregated image data to improve our AI models.`,
        },
        {
          title: '5. Data Sharing & Third Parties',
          body: `We share your information with:\n\n• Supabase (database infrastructure and authentication)\n• OpenAI (AI food analysis — images processed in real-time)\n• RevenueCat (in-app purchase management)\n• Apple App Store / Google Play Store (payment processing)\n• Expo / EAS (app build and update delivery)\n\nWe do not sell your personal data to advertisers or data brokers. We may disclose information if required by law, court order, or to protect the rights and safety of our users.`,
        },
        {
          title: '6. Data Retention',
          body: `We retain your account and food log data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting ${CONTACT_EMAIL}. Upon deletion, your personal data will be permanently removed within 30 days, except where retention is required by law.`,
        },
        {
          title: '7. Data Security',
          body: `We implement industry-standard security measures including TLS encryption for data in transit, AES-256 encryption for data at rest, row-level security in our database, and regular security audits. However, no method of electronic transmission or storage is 100% secure, and we cannot guarantee absolute security.`,
        },
        {
          title: '8. Children\'s Privacy',
          body: `The App is not directed to children under 13 years of age. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected information from a child under 13, please contact us immediately at ${CONTACT_EMAIL}.`,
        },
        {
          title: '9. Your Rights (GDPR / CCPA)',
          body: `Depending on your jurisdiction, you may have the following rights:\n\n• Access: Request a copy of your personal data.\n• Rectification: Correct inaccurate personal data.\n• Erasure: Request deletion of your personal data.\n• Portability: Receive your data in a machine-readable format.\n• Objection: Object to certain processing activities.\n• Opt-out: Opt out of push notifications at any time in device settings.\n\nTo exercise these rights, contact us at ${CONTACT_EMAIL}.`,
        },
        {
          title: '10. Health Data',
          body: `Nutritional and health-related data you enter into the App (weight, dietary goals, allergens) is treated with heightened sensitivity. This data is used solely to provide personalized nutrition tracking features and is never shared with insurance companies, employers, or healthcare providers without your explicit consent. If you choose to sync with Apple Health or Google Fit (Pro feature), data exchange is governed by Apple's and Google's respective privacy frameworks.`,
        },
        {
          title: '11. International Data Transfers',
          body: `Your data may be processed in the United States and other countries where our service providers operate. By using the App, you consent to the transfer of your information to countries outside your country of residence, which may have different data protection rules.`,
        },
        {
          title: '12. Changes to This Policy',
          body: `We may update this Privacy Policy from time to time. We will notify you of material changes through the App or via email. Your continued use of the App after such notification constitutes acceptance of the updated Policy.`,
        },
        {
          title: '13. Contact Us',
          body: `For privacy-related inquiries, data deletion requests, or to exercise your rights:\n\n${COMPANY_NAME}\nPrivacy Officer\nEmail: ${CONTACT_EMAIL}\nWebsite: ${WEBSITE}`,
        },
      ].map(({ title, body }) => (
        <View key={title}>
          <Text style={{ fontSize: 15, fontWeight: '700', color: COLORS.text.primary, marginBottom: 6 }}>
            {title}
          </Text>
          <Text style={{ fontSize: 14, color: COLORS.text.secondary, lineHeight: 22 }}>
            {body}
          </Text>
        </View>
      ))}
    </View>
  );
}

// ============================================================
// Main Legal Screen
// ============================================================
export default function LegalScreen() {
  const { tab } = useLocalSearchParams<{ tab?: string }>();
  const [activeTab, setActiveTab] = useState<'terms' | 'privacy'>(
    tab === 'privacy' ? 'privacy' : 'terms'
  );

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: COLORS.background.DEFAULT }}>
      {/* Header */}
      <View
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          paddingHorizontal: 20,
          paddingVertical: 14,
          borderBottomWidth: 1,
          borderBottomColor: COLORS.border.DEFAULT,
        }}
      >
        <TouchableOpacity onPress={() => router.back()} style={{ marginRight: 12 }}>
          <Text style={{ fontSize: 22, color: COLORS.text.secondary }}>←</Text>
        </TouchableOpacity>
        <Text style={{ fontSize: 18, fontWeight: '700', color: COLORS.text.primary }}>
          Legal
        </Text>
      </View>

      {/* Tab switcher */}
      <View
        style={{
          flexDirection: 'row',
          paddingHorizontal: 20,
          paddingVertical: 12,
          gap: 10,
          borderBottomWidth: 1,
          borderBottomColor: COLORS.border.DEFAULT,
        }}
      >
        {(['terms', 'privacy'] as const).map((t) => (
          <TouchableOpacity
            key={t}
            onPress={() => setActiveTab(t)}
            style={{
              flex: 1,
              paddingVertical: 10,
              borderRadius: 10,
              alignItems: 'center',
              backgroundColor: activeTab === t ? COLORS.primary.DEFAULT : COLORS.background.card,
              borderWidth: 1,
              borderColor: activeTab === t ? COLORS.primary.DEFAULT : COLORS.border.DEFAULT,
            }}
          >
            <Text
              style={{
                fontSize: 14,
                fontWeight: '700',
                color: activeTab === t ? '#FFFFFF' : COLORS.text.secondary,
              }}
            >
              {t === 'terms' ? 'Terms of Service' : 'Privacy Policy'}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <ScrollView
        contentContainerStyle={{ padding: 20, paddingBottom: 60 }}
        showsVerticalScrollIndicator={false}
      >
        {activeTab === 'terms' ? <TermsOfService /> : <PrivacyPolicy />}
      </ScrollView>
    </SafeAreaView>
  );
}
